- hosts: all
  become: true
  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
        
    - name: Upgrade packages
      apt:
        upgrade: dist
        
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        
    - name: Create index.html
      copy:
        content: "Hello, World!"
        dest: /var/www/html/index.html